amcl:
  ros__parameters:
    use_sim_time: false
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    scan_topic: "scan"
    min_particles: 100
    max_particles: 5000
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    laser_model_type: "likelihood_field"
    update_min_d: 0.2
    update_min_a: 0.2
    resample_interval: 1
    transform_tolerance: 1.0

map_server:
  ros__parameters:
    use_sim_time: false
    yaml_filename: ""

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_plugins: ["FollowPath"]
    
    ###### DWB PLANNER #######################
    # FollowPath:
    #   plugin: "dwb_core::DWBLocalPlanner"
    #   debug_trajectory_details: true
    #   min_vel_x: 0.0
    #   min_vel_y: 0.0
    #   max_vel_x: 0.3
    #   max_vel_y: 0.3
    #   max_vel_theta: 0.3
    #   min_speed_xy: 0.0
    #   max_speed_xy: 0.3
    #   min_speed_theta: 0.0
    #   acc_lim_x: 2.5
    #   acc_lim_theta: 3.2
    #   decel_lim_x: -2.5
    #   decel_lim_theta: -3.2

    #   critics: [
    #     "RotateToGoal",
    #     "ObstacleFootprint",
    #     "PathAlign",
    #     "PathDist",
    #     "GoalAlign"
    #   ]

    #   RotateToGoal.scale: 32.0
    #   ObstacleFootprint.scale: 0.01
    #   PathAlign.scale: 32.0
    #   PathDist.scale: 32.0
    #   GoalAlign.scale: 24.0

    ###### REGULATED PURE PURSUIT ############
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.5
      max_angular_vel: 1.0
      min_lookahead_dist: 0.3
      lookahead_time: 1.5
      rotate_to_heading_angular_vel: 0.6

    ###### GRACEFUL ##########################
    # FollowPath:
    #   plugin: "nav2_graceful_controller::GracefulController"
    #   desired_linear_vel: 0.5
    #   min_approach_linear_velocity: 0.25
    #   linear_vel_tol: 0.2
    #   angular_vel_tol: 0.2
    #   transform_tolerance: 0.2
    #   max_angular_accel: 0.2
      
    #   max_lookahead_dist: 1.5
    #   min_lookahead_dist: 0.3
    #   lookahead_time: 2.0

    #   goal_dist_tol: 0.1
    #   use_approach_linear_velocity_scaling: false
    #   use_velocity_scaled_lookahead_dist: false


    #########################################
      
    
    # Goal checker plugin setup
    current_goal_checker: "simple_goal_checker"
    goal_checker_plugins: ["simple_goal_checker"]
    simple_goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"

      ###### DWB PLANNER ####################
      # within 25 cm of first goal (less breaks planner)
      # xy_goal_tolerance: 0.25

      ###### REGULATED PURE PURSUIT #########
      # within 1 cm of first goal
      xy_goal_tolerance: 0.01

      ###### GRACEFUl #######################
      # xy_goal_tolerance: 0.075
      
      #######################################

      yaw_goal_tolerance: 0.05
      stateful: false

    # Progress checker plugin setup
    current_progress_checker: "simple_progress_checker"
    progress_checker_plugins: ["simple_progress_checker"]
    simple_progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0


planner_server:
  ros__parameters:
    use_sim_time: false
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner::NavfnPlanner"
      tolerance: 0.25

bt_navigator:
  ros__parameters:
    use_sim_time: false
    bt_xml_filename: "/opt/ros/jazzy/share/nav2_bt_navigator/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml"
    default_nav_to_pose_bt_xml: "/opt/ros/jazzy/share/nav2_bt_navigator/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml"
    #default_nav_through_poses_bt_xml: "/opt/ros/jazzy/share/nav2_bt_navigator/behavior_trees/navigate_through_poses_w_replanning_and_recovery.xml"
    global_frame: "map"
    robot_base_frame: "base_link"
    # Add these to silence the warning
    follow_path_error_code: 10
    compute_path_error_code: 11
    # Optional error code mapping
    error_code_names:
      - follow_path_error_code
      - compute_path_error_code
      - goal_check_failure_error_code
      - planner_failed_error_code
      - unknown_error_code
    #plugin_lib_names:
      #- nav2_spin_action_bt_node
      #- nav2_compute_path_to_pose_action_bt_node
      #- nav2_follow_path_action_bt_node
      #- nav2_spin_action_bt_node  # <- This one is missing!
      #- nav2_wait_action_bt_node
      #- nav2_back_up_action_bt_node
      #- nav2_clear_costmap_service_bt_node


waypoint_follower:
  ros__parameters:
    use_sim_time: false
    loop_rate: 20
    stop_on_failure: true

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: false
      global_frame: "odom"
      robot_base_frame: "base_link"
      update_frequency: 5.0
      publish_frequency: 2.0
      resolution: 0.05
      width: 6           # <-- Add this
      height: 6          # <-- And this
      rolling_window: true           # <-- This keeps robot centered
      robot_radius: 0.2
      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.5

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: false
      global_frame: "map"
      robot_base_frame: "base_link"
      update_frequency: 1.0
      publish_frequency: 1.0
      resolution: 0.05
      robot_radius: 0.2
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: true
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.5