#
#-----------------------------
#  \\       //   \\       // 
#    \\   //       \\   //   
#  ^   ===           ===     
#  x                         
#                            

poses:
 -
   id: 0
   x: 1.37
   y: 0.0
   z: 0.0
   roll: 0.0
   pitch: 0.0
   yaw: -20.0
 -
   id: 1
   x: 1.37
   y: 0.0
   z: -0.5
   roll: 0.0
   pitch: 0.0
   yaw: -20.0
 -
   id: 0
   x: 1.37
   y: 0.0
   z: 0.0
   roll: 0.0
   pitch: 0.0
   yaw: -20.0
 -
   id: 2
   x: 1.026
   y: -0.940
   z: 0.0
   roll: 0.0
   pitch: 0.0
   yaw: -20.0
 -
   id: 3
   x: 1.026
   y: -0.940
   z: -0.5
   roll: 0.0
   pitch: 0.0
   yaw: -20.0
 -
   id: 2
   x: 1.026
   y: -0.940
   z: 0.0
   roll: 0.0
   pitch: 0.0
   yaw: -20.0
 -
   id: 4
   x: 0.684
   y: -1.88
   z: 0.0
   roll: 0.0
   pitch: 0.0
   yaw: -20.0
 -
   id: 5
   x: 0.684
   y: -1.88
   z: -0.5
   roll: 0.0
   pitch: 0.0
   yaw: -20.0
 -
   id: 4
   x: 0.684
   y: -1.88
   z: 0.0
   roll: 0.0
   pitch: 0.0
   yaw: -20.0


# MID POINT Fence 1
 -
   id: 6
   x: 0.513
   y: -2.38
   z: 0.0
   roll: 0.0
   pitch: 0.0
   yaw: 0.0
 -
   id: 7
   x: 0.513
   y: -2.38
   z: -0.5
   roll: 0.0
   pitch: 0.0
   yaw: 0.0
 -
   id: 6
   x: 0.513
   y: -2.38
   z: 0.0
   roll: 0.0
   pitch: 0.0
   yaw: 0.0


#############


 -
   id: 8
   x: 0.684
   y: -2.88
   z: 0.0
   roll: 0.0
   pitch: 0.0
   yaw: 20.0
 -
   id: 9
   x: 0.684
   y: -2.88
   z: -0.5
   roll: 0.0
   pitch: 0.0
   yaw: 20.0
 -
   id: 8
   x: 0.684
   y: -2.88
   z: 0.0
   roll: 0.0
   pitch: 0.0
   yaw: 20.0
 -
   id: 10
   x: 1.026
   y: -3.82
   z: 0.0
   roll: 0.0
   pitch: 0.0
   yaw: 20.0
 -
   id: 11
   x: 1.026
   y: -3.82
   z: -0.5
   roll: 0.0
   pitch: 0.0
   yaw: 20.0
 -
   id: 10
   x: 1.026
   y: -3.82
   z: 0.0
   roll: 0.0
   pitch: 0.0
   yaw: 20.0
 -
   id: 12
   x: 1.37
   y: -4.76
   z: 0.0
   roll: 0.0
   pitch: 0.0
   yaw: 20.0
 -
   id: 13
   x: 1.37
   y: -4.76
   z: -0.5
   roll: 0.0
   pitch: 0.0
   yaw: 20.0
 -
   id: 12
   x: 1.37
   y: -4.76
   z: 0.0
   roll: 0.0
   pitch: 0.0
   yaw: 20.0




### Second Fence ###
 -
   id: 14
   x: 1.37
   y: -6.26
   z: 0.0
   roll: 0.0
   pitch: 0.0
   yaw: -20.0
 -
   id: 15
   x: 1.37
   y: -6.26
   z: -0.5
   roll: 0.0
   pitch: 0.0
   yaw: -20.0
 -
   id: 14
   x: 1.37
   y: -6.26
   z: 0.0
   roll: 0.0
   pitch: 0.0
   yaw: -20.0
 -
   id: 16
   x: 1.026
   y: -7.20
   z: 0.0
   roll: 0.0
   pitch: 0.0
   yaw: -20.0
 -
   id: 17
   x: 1.026
   y: -7.2
   z: -0.5
   roll: 0.0
   pitch: 0.0
   yaw: -20.0
 -
   id: 16
   x: 1.026
   y: -7.2
   z: 0.0
   roll: 0.0
   pitch: 0.0
   yaw: -20.0
 -
   id: 18
   x: 0.684
   y: -8.14
   z: 0.0
   roll: 0.0
   pitch: 0.0
   yaw: -20.0
 -
   id: 19
   x: 0.684
   y: -8.14
   z: -0.5
   roll: 0.0
   pitch: 0.0
   yaw: -20.0
 -
   id: 18
   x: 0.684
   y: -8.14
   z: 0.0
   roll: 0.0
   pitch: 0.0
   yaw: -20.0


# MID POINT Fence 2
 -
   id: 20
   x: 0.513
   y: -8.64
   z: 0.0
   roll: 0.0
   pitch: 0.0
   yaw: 0.0
 -
   id: 21
   x: 0.513
   y: -8.64
   z: -0.5
   roll: 0.0
   pitch: 0.0
   yaw: 0.0
 -
   id: 20
   x: 0.513
   y: -8.64
   z: 0.0
   roll: 0.0
   pitch: 0.0
   yaw: 0.0


#############


 -
   id: 22
   x: 0.684
   y: -9.14
   z: 0.0
   roll: 0.0
   pitch: 0.0
   yaw: 20.0
 -
   id: 23
   x: 0.684
   y: -9.14
   z: -0.5
   roll: 0.0
   pitch: 0.0
   yaw: 20.0
 -
   id: 22
   x: 0.684
   y: -9.14
   z: 0.0
   roll: 0.0
   pitch: 0.0
   yaw: 20.0
 -
   id: 24
   x: 1.026
   y: -10.08
   z: 0.0
   roll: 0.0
   pitch: 0.0
   yaw: 20.0
 -
   id: 25
   x: 1.026
   y: -10.08
   z: -0.5
   roll: 0.0
   pitch: 0.0
   yaw: 20.0
 -
   id: 24
   x: 1.026
   y: -10.08
   z: 0.0
   roll: 0.0
   pitch: 0.0
   yaw: 20.0
 -
   id: 26
   x: 1.37
   y: -11.02
   z: 0.0
   roll: 0.0
   pitch: 0.0
   yaw: 20.0
 -
   id: 27
   x: 1.37
   y: -11.02
   z: -0.5
   roll: 0.0
   pitch: 0.0
   yaw: 20.0
 -
   id: 26
   x: 1.37
   y: -11.02
   z: 0.0
   roll: 0.0
   pitch: 0.0
   yaw: 20.0
