poses:
  -
    id: 0
    x: 1.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  -
    id: 1
    x: 1.0
    y: 0.0
    z: -0.5
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  -
    id: 0
    x: 1.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  -
    id: 2
    x: 1.0
    y: 1.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  -
    id: 3
    x: 1.0
    y: 1.0
    z: -0.5
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  -
    id: 2
    x: 1.0
    y: 1.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  -
    id: 4
    x: 1.0
    y: 2.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  -
    id: 5
    x: 1.0
    y: 2.0
    z: -0.5
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  -
    id: 4
    x: 1.0
    y: 2.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0